a = input('digite algo:')
print('0 tipo primitivo desse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('It s a number?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Is in capital letters?', a.isupper())
print('Is in lowercase?', a.islower())
print('Its capitalized?', a.istitle())
